export const rows = [
  {
    region: "Mumbai",
    id: "75hkjuz94",
    status: "Charging",
    totaltraveled: 3263,
    avgconsumption: 402.69,
    avgconsumption: 5,
    avg_payload: 26,
    value: 1,
  },
  {
    region: "Mumbai",
    id: "33xynab56",
    status: "Offline",
    totaltraveled: 96961,
    avgconsumption: 146.16,
    avgconsumption: 5,
    avg_payload: 26,
    value: 2,
  },
  {
    region: "Mumbai",
    id: "75hkjuz94",
    status: "Trip",
    totaltraveled: 3040,
    avgconsumption: 200.85,
    avgconsumption: "",
    avg_payload: 26,
    value: 3,
  },
  {
    region: "Mumbai",
    id: "6mvgew05",
    status: "Offline",
    totaltraveled: 3520,
    avgconsumption: 33.26,
    avgconsumption: 5,
    avg_payload: 26,
    value: 4,
  },
  {
    region: "Mumbai",
    id: "6mvgew05",
    status: "Charging",
    totaltraveled: 670,
    avgconsumption: 3.77,
    avgconsumption: 5,
    avg_payload: 26,
    value: 5,
  },
  {
    region: "Mumbai",
    id: "75hkjuz94",
    status: "Parked",
    totaltraveled: 76024,
    avgconsumption: 3.31,
    avgconsumption: "",
    avg_payload: 26,
    value: 6,
  },
  {
    region: "Mumbai",
    id: "33xynab56",
    status: "Charging",
    totaltraveled: 358,
    avgconsumption: 232.21,
    avgconsumption: "",
    avg_payload: 26,
    value: 7,
  },
  {
    region: "Mumbai",
    id: "75hkjuz94",
    status: "Offline",
    totaltraveled: 773,
    avgconsumption: 69.13,
    avgconsumption: 5,
    avg_payload: 26,
    value: 8,
  },
  {
    region: "Mumbai",
    id: "33xynab56",
    status: "Charging",
    totaltraveled: 358,
    avgconsumption: 232.21,
    avgconsumption: "",
    avg_payload: 26,
    value: 7,
  },
  {
    region: "Mumbai",
    id: "75hkjuz94",
    status: "Offline",
    totaltraveled: 773,
    avgconsumption: 69.13,
    avgconsumption: 5,
    avg_payload: 26,
    value: 8,
  },
  // { region: 'Mexico', id: 'MX', currentstatus: 126577691,totaltraveled: 1972550, avgconsumption: 64.18 ,avgconsumption:5,avg_payload:26,value:9},
  // { region: 'Japan', id: 'JP', currentstatus: 126317000, totaltraveled: 377973, avgconsumption: 334.38 ,avgconsumption:5,avg_payload:26,value:10},
  // { region: 'France', id: 'FR', currentstatus: 67022000, totaltraveled: 640679, avgconsumption: 104.62 ,avgconsumption:5,avg_payload:26,value:11},
  // { region: 'United Kingdom', id: 'GB', currentstatus: 67545757, totaltraveled: 242495, avgconsumption: 278.39,avgconsumption:5,avg_payload:26,value:12 },
  // { region: 'Russia', id: 'RU', currentstatus: 146793744, totaltraveled: 17098246, avgconsumption: 8.58 ,avgconsumption:5,avg_payload:26,value:13},
  // { region: 'Nigeria', id: 'NG', currentstatus: 200962417, totaltraveled: 923768, avgconsumption: 217.46,avgconsumption:5,avg_payload:26 ,value:14},
  // { region: 'Brazil', id: 'BR', currentstatus: 210147125, totaltraveled: 8515767, avgconsumption: 24.67,avgconsumption:5,avg_payload:26,value:15 },
];
export const Fleet = [
  // { region: 'India', VehicleId: 'IN', status: "charging", avgSpeed: 3287263,avgPayload: 402.69 ,avgconsumption:5,avg_payload:26,value:1,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'China', VehicleId: 'CN', status: 'charging', avgSpeed: 9596961, avgPayload: 146.16 ,avgconsumption:5,avg_payload:26,value:2,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Italy', VehicleId: 'IT', status: 'Parked', avgSpeed: 301340, avgPayload: 200.85,avgconsumption:5,avg_payload:26 ,value:3,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'United States', VehicleId: 'US', status: 'Trip', avgSpeed: 9833520, avgPayload: 33.26,avgconsumption:5,avg_payload:26 ,value:4,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Canada', VehicleId: 'CA', status: "charging", avgSpeed: 9984670, avgPayload: 3.77 ,avgconsumption:5,avg_payload:26,value:5,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Australia', VehicleId: 'AU', status: 'charging', avgSpeed: 7692024, avgPayload: 3.31 ,avgconsumption:5,avg_payload:26,value:6,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Germany', VehicleId: 'DE', status: "charging", avgSpeed: 357578, avgPayload: 232.21,avgconsumption:5,avg_payload:26 ,value:7,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Ireland', VehicleId: 'IE', status: "charging", avgSpeed: 70273, avgPayload: 69.13 ,avgconsumption:5,avg_payload:26,value:8,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Mexico', VehicleId: 'MX', status: "charging",avgSpeed: 1972550,avgPayload: 64.18 ,avgconsumption:5,avg_payload:26,value:9,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Japan', VehicleId: 'JP', status: 'Trip', avgSpeed: 377973, avgPayload: 334.38 ,avgconsumption:5,avg_payload:26,value:10,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'France', VehicleId: 'FR', status: "Trip", avgSpeed: 640679, avgPayload: 104.62 ,avgconsumption:5,avg_payload:26,value:11,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'United Kingdom', VehicleId: 'GB', status: "Trip", avgSpeed: 242495, avgPayload: 278.39,avgconsumption:5,avg_payload:26,value:12,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
  // { region: 'Russia', VehicleId: 'RU', status: "Trip", avgSpeed: 17098246, avgPayload: 8.58 ,avgconsumption:5,avg_payload:26,value:13,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Nigeria', VehicleId: 'NG', status: "Trip", avgSpeed: 923768, avgPayload: 217.46,avgconsumption:5,avg_payload:26 ,value:14,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Brazil', VehicleId: 'BR', status: "Trip", avgSpeed: 8515767, avgPayload: 24.67,avgconsumption:5,avg_payload:26,value:15,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
];
export const Trip = [
  {
    region: "India",
    VehicleId: "IN",
    status: "charging",
    avgSpeed: 3287263,
    avgPayload: 402.69,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 1,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "China",
    VehicleId: "CN",
    status: "charging",
    avgSpeed: 9596961,
    avgPayload: 146.16,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 2,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Italy",
    VehicleId: "IT",
    status: "Parked",
    avgSpeed: 301340,
    avgPayload: 200.85,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 3,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "United States",
    VehicleId: "US",
    status: "Trip",
    avgSpeed: 9833520,
    avgPayload: 33.26,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 4,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Canada",
    VehicleId: "CA",
    status: "charging",
    avgSpeed: 9984670,
    avgPayload: 3.77,
    TotalTripDay: 50,
    TotalTripmonth: 26,
    value: 5,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Australia",
    VehicleId: "AU",
    status: "charging",
    avgSpeed: 7692024,
    avgPayload: 3.31,
    TotalTripDay: 596,
    TotalTripmonth: 26,
    value: 6,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Germany",
    VehicleId: "DE",
    status: "charging",
    avgSpeed: 357578,
    avgPayload: 232.21,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 7,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Ireland",
    VehicleId: "IE",
    status: "charging",
    avgSpeed: 70273,
    avgPayload: 69.13,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 8,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Mexico",
    VehicleId: "MX",
    status: "charging",
    avgSpeed: 1972550,
    avgPayload: 64.18,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 9,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Japan",
    VehicleId: "JP",
    status: "Trip",
    avgSpeed: 377973,
    avgPayload: 334.38,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 10,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "France",
    VehicleId: "FR",
    status: "Trip",
    avgSpeed: 640679,
    avgPayload: 104.62,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 11,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "United Kingdom",
    VehicleId: "GB",
    status: "Trip",
    avgSpeed: 242495,
    avgPayload: 278.39,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 12,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Russia",
    VehicleId: "RU",
    status: "Trip",
    avgSpeed: 17098246,
    avgPayload: 8.58,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 13,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Nigeria",
    VehicleId: "NG",
    status: "Trip",
    avgSpeed: 923768,
    avgPayload: 217.46,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 14,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Brazil",
    VehicleId: "BR",
    status: "Trip",
    avgSpeed: 8515767,
    avgPayload: 24.67,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 15,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
];
export const ChargingStationRow = [
  {
    region: "75hkjuz94",
    Id: "IN",
    status: "Online",
    avgSpeed: 3287263,
    avgPayload: 402.69,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 1,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "75hkjuz94",
    Id: "CN",
    status: "Offline",
    avgSpeed: 9596961,
    avgPayload: 146.16,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 2,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "75hkjuz94",
    Id: "IT",
    status: "Offile",
    avgSpeed: 301340,
    avgPayload: 200.85,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 3,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "75hkjuz94 ",
    Id: "US",
    status: "Online",
    avgSpeed: 9833520,
    avgPayload: 33.26,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 4,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "",
    Id: "CA",
    status: "Online",
    avgSpeed: 9984670,
    avgPayload: 3.77,
    TotalTripDay: 50,
    TotalTripmonth: 26,
    value: 5,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "",
    Id: "AU",
    status: "Offline",
    avgSpeed: 7692024,
    avgPayload: 3.31,
    TotalTripDay: 596,
    TotalTripmonth: 26,
    value: 6,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "",
    Id: "DE",
    status: "Offline",
    avgSpeed: 357578,
    avgPayload: 232.21,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 7,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "",
    Id: "IE",
    status: "Online",
    avgSpeed: 70273,
    avgPayload: 69.13,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 8,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "75hkjuz94",
    Id: "MX",
    status: "Offline",
    avgSpeed: 1972550,
    avgPayload: 64.18,
    TotalTripDay: 5,
    TotalTripmonth: 26,
    value: 9,
    breakdown: 61,
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  // { region: 'Japan',Id: 'JP', status: 'Ofiilne', avgSpeed: 377973, avgPayload: 334.38 ,TotalTripDay:5,TotalTripmonth:26,value:10,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'France',Id: 'FR', status: "Ofiilne", avgSpeed: 640679, avgPayload: 104.62 ,TotalTripDay:5,TotalTripmonth:26,value:11,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'United Kingdom',Id: 'GB', status:"Online", avgSpeed: 242495, avgPayload: 278.39,TotalTripDay:5,TotalTripmonth:26,value:12,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
  // { region: 'Russia',Id: 'RU', status:"Online", avgSpeed: 17098246, avgPayload: 8.58 ,TotalTripDay:5,TotalTripmonth:26,value:13,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Nigeria',Id: 'NG', status: "Ofiilne", avgSpeed: 923768, avgPayload: 217.46,TotalTripDay:5,TotalTripmonth:26 ,value:14,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Brazil',Id: 'BR', status: "Ofiilne", avgSpeed: 8515767, avgPayload: 24.67,TotalTripDay:5,TotalTripmonth:26,value:15,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
];
export const E_tractorData = [
  {
    region: "India",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 3287263,
    swappingcycle: 402.69,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 1,
    selectedpackage: "fusion A",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "China",
    Id: "75hkjuz94",
    status: "Available",
    avgSpeed: 9596961,
    swappingcycle: 146.16,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 2,
    selectedpackage: "fusion B",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Italy",
    Id: "75hkjuz94",
    status: "Available",
    avgSpeed: 301340,
    swappingcycle: 200.85,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 3,
    selectedpackage: "fusion C",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "United States",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 9833520,
    swappingcycle: 33.26,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 4,
    selectedpackage: "fusion D",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Canada",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 9984670,
    swappingcycle: 3.77,
    chargingcycle: 50,
    TotalTripmonth: 26,
    value: 5,
    selectedpackage: "fusion E",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  // { region: 'Australia',Id: 'AU', status: 'charging', avgSpeed: 7692024, chargingcycle: 3.31 ,TotalTripDay:596,TotalTripmonth:26,value:6,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Germany',Id: 'DE', status: "charging", avgSpeed: 357578, chargingcycle: 232.21,TotalTripDay:5,TotalTripmonth:26 ,value:7,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Ireland',Id: 'IE', status: "charging", avgSpeed: 70273, chargingcycle: 69.13 ,TotalTripDay:5,TotalTripmonth:26,value:8,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Mexico',Id: 'MX', status: "charging",avgSpeed: 1972550,chargingcycle: 64.18 ,TotalTripDay:5,TotalTripmonth:26,value:9,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Japan',Id: 'JP', status: 'Trip', avgSpeed: 377973, chargingcycle: 334.38 ,TotalTripDay:5,TotalTripmonth:26,value:10,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'France',Id: 'FR', status: "Trip", avgSpeed: 640679, chargingcycle: 104.62 ,TotalTripDay:5,TotalTripmonth:26,value:11,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'United Kingdom',Id: 'GB', status: "Trip", avgSpeed: 242495, chargingcycle: 278.39,TotalTripDay:5,TotalTripmonth:26,value:12,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
  // { region: 'Russia',Id: 'RU', status: "Trip", avgSpeed: 17098246, chargingcycle: 8.58 ,TotalTripDay:5,TotalTripmonth:26,value:13,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Nigeria',Id: 'NG', status: "Trip", avgSpeed: 923768, chargingcycle: 217.46,TotalTripDay:5,TotalTripmonth:26 ,value:14,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Brazil',Id: 'BR', status: "Trip", avgSpeed: 8515767, chargingcycle: 24.67,TotalTripDay:5,TotalTripmonth:26,value:15,breakdown:61,currentsoc:9,estimated:52,schedulingstatus:89, },
];
export const RevenueManagementData = [
  {
    region: "India",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 3287263,
    swappingcycle: 402.69,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 1,
    selectedpackage: "fusion A",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "China",
    Id: "75hkjuz94",
    status: "Available",
    avgSpeed: 9596961,
    swappingcycle: 146.16,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 2,
    selectedpackage: "fusion B",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Italy",
    Id: "75hkjuz94",
    status: "Available",
    avgSpeed: 301340,
    swappingcycle: 200.85,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 3,
    selectedpackage: "fusion C",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "United States",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 9833520,
    swappingcycle: 33.26,
    chargingcycle: 5,
    TotalTripmonth: 26,
    value: 4,
    selectedpackage: "fusion D",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  {
    region: "Canada",
    Id: "75hkjuz94",
    status: "Occupied",
    avgSpeed: 9984670,
    swappingcycle: 3.77,
    chargingcycle: 50,
    TotalTripmonth: 26,
    value: 5,
    selectedpackage: "fusion E",
    currentsoc: 9,
    estimated: 52,
    schedulingstatus: 89,
  },
  // { region: 'Australia',Id: 'AU', status: 'charging', avgSpeed: 7692024, swappingcycle: 3.31, chargingcycle:596,TotalTripmonth:26,value:6,selectedpackage:"fusion F",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Germany',Id: 'DE', status: "charging", avgSpeed: 357578, swappingcycle: 232.21,chargingcycle:5,TotalTripmonth:26 ,value:7,selectedpackage:"fusion G",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Ireland',Id: 'IE', status: "charging", avgSpeed: 70273, swappingcycle: 69.13 ,chargingcycle:5,TotalTripmonth:26,value:8,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Mexico',Id: 'MX', status: "charging",avgSpeed: 1972550,swappingcycle: 64.18 ,chargingcycle:5,TotalTripmonth:26,value:9,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Japan',Id: 'JP', status: 'Trip', avgSpeed: 377973, swappingcycle: 334.38 ,chargingcycle:5,TotalTripmonth:26,value:10,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'France',Id: 'FR', status: "Trip", avgSpeed: 640679, swappingcycle: 104.62 ,chargingcycle:5,TotalTripmonth:26,value:11,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'United Kingdom',Id: 'GB', status: "Trip", avgSpeed: 242495, swappingcycle: 278.39,chargingcycle:5,TotalTripmonth:26,value:12,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89, },
  // { region: 'Russia',Id: 'RU', status: "Trip", avgSpeed: 17098246, swappingcycle: 8.58 ,chargingcycle:5,TotalTripmonth:26,value:13,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Nigeria',Id: 'NG', status: "Trip", avgSpeed: 923768, swappingcycle: 217.46,chargingcycle:5,TotalTripmonth:26 ,value:14,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89,},
  // { region: 'Brazil',Id: 'BR', status: "Trip", avgSpeed: 8515767, swappingcycle: 24.67,chargingcycle:5,TotalTripmonth:26,value:15,selectedpackage:"fusion A",currentsoc:9,estimated:52,schedulingstatus:89, },
];
export const dummyTariff = [
  {
    employeeId: "49zalcd28",
    color: "#C0FE72",
    status: "Tariff 1",
    lastName: "7",
    mobileNumber: "-1.5",
    mobileNumber1: "-5.5",
    mobileNumber2: "-2.5",
    mobileNumber3: "6.8",
  },
  {
    employeeId: "49zalcd28",
    color: "#FF5722",
    status: "Tariff 1",
    lastName: "7",
    mobileNumber: "-1.5",
    mobileNumber1: "-5.5",
    mobileNumber2: "-2.5",
    mobileNumber3: "5.5",
  },
  {
    employeeId: "49zalcd28",
    color: "#3F51B5",
    status: "Tariff 1",
    lastName: "7",
    mobileNumber: "-1.5",
    mobileNumber1: "-5.5",
    mobileNumber2: "-2.5",
    mobileNumber3: "8.5",
  },
];

export const dummyCustomerData = [
  {
    portId: "P001",
    color: "#C0FE72",
    name: "Port Alpha",
    regionName: "North",
    customer: "John Doe",
    tariff: "Tariff ",
  },
  {
    portId: "P002",
    color: "#FF5722",
    name: "Port Beta",
    regionName: "East",
    customer: "Jane Smith",
    tariff: "Tariff ",
  },
  {
    portId: "P003",
    color: "#3F51B5",
    name: "Port Gamma",
    regionName: "West",
    customer: "Alice Johnson",
    tariff: "Tariff ",
  },
];
export const dummyData = [
  {
    batteryId: "B001",
    region: "North",
    status: "Available",
    queue: "--",
    maxCapacity: "--",
    currentCharging: "--",
    ETractor: "E1234",
    lastSessionStarted: "14 Min Ago",
    alerts: "None",
    jobRole: "Technician",
  },
  {
    batteryId: "B002",
    region: "South",
    status: "Down",
    queue: "--",
    maxCapacity: "85%",
    currentCharging: "40%",
    ETractor: "E5678",
    lastSessionStarted: "14 Min Ago",
    alerts: "Maintenance due",
  },
  {
    batteryId: "B003",
    region: "East",
    status: "Finish",
    queue: "--",
    maxCapacity: "--",
    currentCharging: "--",
    ETractor: "E9101",
    lastSessionStarted: "14 Min Ago",
    alerts: "None",
  },
  {
    batteryId: "B004",
    region: "East",
    status: "In Charging",
    queue: "--",
    maxCapacity: "--",
    currentCharging: "--",
    ETractor: "E9101",
    lastSessionStarted: "14 Min Ago",
    alerts: "Low Capacity",
  },
];

export const particularBatteryData = [
  {
    date: "2024-07-29",
    temperature: 25.3,
    voltage: 3.7,
    soc: 85,
    soh: 95,
    error: "None",
  },
  {
    date: "2024-07-28",
    temperature: 27.1,
    voltage: 3.8,
    soc: 80,
    soh: 93,
    error: "Low Voltage",
  },
  {
    date: "2024-07-27",
    temperature: 26.4,
    voltage: 3.6,
    soc: 78,
    soh: 92,
    error: "Over Temperature",
  },
  {
    date: "2024-07-26",
    temperature: 24.8,
    voltage: 3.7,
    soc: 82,
    soh: 94,
    error: "None",
  },
];
